spring.application.name=springcodespace

spring.datasource.url = jdbc:mysql://localhost:3306/ems
spring.datasource.username = springuser
spring.datasource.password = password

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

server.port=9999